### ISSUE TITLE
Chocolatey automated package failure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-metanorma#17]
Current status = Waiting for Maintainer to take corrective action

chocolatey-ops left the following comment(s):

metanorma has failed automated testing.
This is not the only check that is performed so check the package page to ensure a 'Ready' status.
Please visit https://gist.github.com/5b4128876df6e776deabd92ed6ec2046 for details.
The package status will be changed and will be waiting on your next actions.

NEW! We have a test environment for you to replicate the testing we do. This can be used at any time to test packages! See https://github.com/chocolatey/chocolatey-test-environment
Please log in and leave a review comment if you have questions and/or comments.
If you see the verifier needs to rerun testing against the package without resubmitting (a issue in the test results), you can do that on the package page in the review section.
If the verifier is incompatible with the package, please log in and leave a review comment if the package needs to bypass testing (e.g. package installs specific drivers).
Automated testing can also fail when a package is not completely silent or has pop ups (AutoHotKey can assist - a great example is the VeraCrypt package).
A package that cannot be made completely unattended should have the notSilent tag. Note that this must be approved by moderators.

Attention - DO NOT REPLY TO THIS MESSAGE!

No human moderators see packages until automated checks are passed or the maintainer uses the review comments box to respond. This is very important to understand, if a package has failed any automated checks, you must take action to fix or respond.
ATTENTION: If your package is failing any automated checks, the ONLY way to get in front of a human moderator is to follow the instructions in the next step.
If you need to update or respond to package review information, please login and visit your package page (listed below). Use the Add to Review Comments box ONLY, Disqus/Gist comments will not reach a human reviewer.
This may include review comments prior to the automated checks, check the status on the package - it must be in 'Ready' or 'Responded' to be in front of a human moderator.
You can also self-reject packages in certain scenarios - see self-reject for more information.
Package Url: https://chocolatey.org/packages/metanorma/1.1.4 
Maintainer(s): ribose

Maintainer Notes

If we've asked you to make changes, repush your updated package with the exact same version (unless the change we requested was based on an incorrect version).

**Comment by ronaldtse** [comment]
The link to the failure is here: https://gist.github.com/choco-bot/5b4128876df6e776deabd92ed6ec2046

**Comment by ronaldtse** [comment]
The failure notice says:

```
2019-02-15 17:48:04,824 2228 [WARN ] - 
Chocolatey installed 14/16 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-02-15 17:48:04,824 2228 [INFO ] - 
2019-02-15 17:48:04,839 2228 [WARN ] - Installed:
2019-02-15 17:48:04,839 2228 [INFO ] -  - plantuml v1.2019.1
2019-02-15 17:48:04,855 2228 [INFO ] -  - jre8 v8.0.201
2019-02-15 17:48:04,855 2228 [INFO ] -  - git v2.20.1
2019-02-15 17:48:04,855 2228 [INFO ] -  - sed v4.5
2019-02-15 17:48:04,871 2228 [INFO ] -  - metanorma v1.1.4
2019-02-15 17:48:04,871 2228 [INFO ] -  - ruby v2.5.3.101
2019-02-15 17:48:04,871 2228 [INFO ] -  - nodejs v11.10.0
2019-02-15 17:48:04,871 2228 [INFO ] -  - chocolatey-core.extension v1.3.3
2019-02-15 17:48:04,886 2228 [INFO ] -  - nodejs.install v11.10.0
2019-02-15 17:48:04,886 2228 [INFO ] -  - xsltproc v1.1.28.0
2019-02-15 17:48:04,886 2228 [INFO ] -  - javaruntime v8.0.191
2019-02-15 17:48:04,902 2228 [INFO ] -  - msys2 v20180531.0.0
2019-02-15 17:48:04,902 2228 [INFO ] -  - graphviz v2.38.0.20190211
2019-02-15 17:48:04,902 2228 [INFO ] -  - git.install v2.20.1
2019-02-15 17:48:04,902 2228 [INFO ] - 
2019-02-15 17:48:04,918 2228 [ERROR] - Failures
2019-02-15 17:48:04,918 2228 [ERROR] -  - gnuwin32-coreutils.portable (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\gnuwin32-coreutils.portable\tools\chocolateyinstall.ps1'.
 See log for details.
2019-02-15 17:48:04,918 2228 [ERROR] -  - make (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\make\tools\chocolateyinstall.ps1'.
 See log for details.
2019-02-15 17:48:04,933 2228 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2019-02-15 17:48:05,121 2228 [DEBUG] - Exiting with 404
```

**Comment by CAMOBAP795** [comment]
@ronaldtse looks like temporally network issue I have retagged last commit to initiate `choco push` again

**Comment by ronaldtse** [comment]
@CAMOBAP795 it has died again:

```
'metanorma' is Submitted.
Current status = Waiting for Maintainer to take corrective action

chocolatey-ops left the following comment(s):

metanorma has failed automated testing.
This is not the only check that is performed so check the package page to ensure a 'Ready' status.
Please visit https://gist.github.com/1c568f7839fde19460f5786dfc454c5e for details.
The package status will be changed and will be waiting on your next actions.

NEW! We have a test environment for you to replicate the testing we do. This can be used at any time to test packages! See https://github.com/chocolatey/chocolatey-test-environment
Please log in and leave a review comment if you have questions and/or comments.
If you see the verifier needs to rerun testing against the package without resubmitting (a issue in the test results), you can do that on the package page in the review section.
If the verifier is incompatible with the package, please log in and leave a review comment if the package needs to bypass testing (e.g. package installs specific drivers).
Automated testing can also fail when a package is not completely silent or has pop ups (AutoHotKey can assist - a great example is the VeraCrypt package).
A package that cannot be made completely unattended should have the notSilent tag. Note that this must be approved by moderators.

Attention - DO NOT REPLY TO THIS MESSAGE!

No human moderators see packages until automated checks are passed or the maintainer uses the review comments box to respond. This is very important to understand, if a package has failed any automated checks, you must take action to fix or respond.
ATTENTION: If your package is failing any automated checks, the ONLY way to get in front of a human moderator is to follow the instructions in the next step.
If you need to update or respond to package review information, please login and visit your package page (listed below). Use the Add to Review Comments box ONLY, Disqus/Gist comments will not reach a human reviewer.
This may include review comments prior to the automated checks, check the status on the package - it must be in 'Ready' or 'Responded' to be in front of a human moderator.
You can also self-reject packages in certain scenarios - see self-reject for more information.
Package Url: https://chocolatey.org/packages/metanorma/1.1.4 
Maintainer(s): ribose

Maintainer Notes

If we've asked you to make changes, repush your updated package with the exact same version (unless the change we requested was based on an incorrect version).
```

**Comment by ronaldtse** [comment]
The network failure:

```
2019-02-16 12:37:11,799 2012 [WARN ] - WARNING: Url has SSL/TLS available, switching to HTTPS for download
2019-02-16 12:37:11,799 2012 [DEBUG] - Running Get-WebFileName -url 'https://sourceforge.net/projects/gnuwin32/files/coreutils/5.3.0/coreutils-5.3.0-bin.zip' -defaultName 'gnuwin32-coreutils.portableInstall.zip' 
2019-02-16 12:37:42,924 2012 [DEBUG] - Url request/response failed - file name will be 'gnuwin32-coreutils.portableInstall.zip':  Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
2019-02-16 12:37:42,940 2012 [DEBUG] - Running Get-WebHeaders -url 'https://sourceforge.net/projects/gnuwin32/files/coreutils/5.3.0/coreutils-5.3.0-bin.zip' -ErrorAction 'Stop' 
```

This network failure is real: https://sourceforge.net/projects/gnuwin32/files/coreutils/5.3.0/coreutils-5.3.0-bin.zip isn't loadable?

**Comment by CAMOBAP795** [comment]
I checked from browser there is delay (10-15 sec) but it works, 

Let me try to do the same at night (EU night)

**Comment by ronaldtse** [comment]
@CAMOBAP795 failed again:

```
'metanorma' is Submitted.
Current status = Waiting for Maintainer to take corrective action

chocolatey-ops left the following comment(s):

metanorma has failed automated testing.
This is not the only check that is performed so check the package page to ensure a 'Ready' status.
Please visit https://gist.github.com/f5de5355839a3b3f438cfe32b6532c55 for details.
The package status will be changed and will be waiting on your next actions.

NEW! We have a test environment for you to replicate the testing we do. This can be used at any time to test packages! See https://github.com/chocolatey/chocolatey-test-environment
Please log in and leave a review comment if you have questions and/or comments.
If you see the verifier needs to rerun testing against the package without resubmitting (a issue in the test results), you can do that on the package page in the review section.
If the verifier is incompatible with the package, please log in and leave a review comment if the package needs to bypass testing (e.g. package installs specific drivers).
Automated testing can also fail when a package is not completely silent or has pop ups (AutoHotKey can assist - a great example is the VeraCrypt package).
A package that cannot be made completely unattended should have the notSilent tag. Note that this must be approved by moderators.

Attention - DO NOT REPLY TO THIS MESSAGE!

No human moderators see packages until automated checks are passed or the maintainer uses the review comments box to respond. This is very important to understand, if a package has failed any automated checks, you must take action to fix or respond.
ATTENTION: If your package is failing any automated checks, the ONLY way to get in front of a human moderator is to follow the instructions in the next step.
If you need to update or respond to package review information, please login and visit your package page (listed below). Use the Add to Review Comments box ONLY, Disqus/Gist comments will not reach a human reviewer.
This may include review comments prior to the automated checks, check the status on the package - it must be in 'Ready' or 'Responded' to be in front of a human moderator.
You can also self-reject packages in certain scenarios - see self-reject for more information.
Package Url: https://chocolatey.org/packages/metanorma/1.1.4 
Maintainer(s): ribose

Maintainer Notes

If we've asked you to make changes, repush your updated package with the exact same version (unless the change we requested was based on an incorrect version).
```

**Comment by ronaldtse** [comment]
@CAMOBAP795 maybe we can try again -- I can access the sourceforge link now.

**Comment by CAMOBAP795** [comment]
I propose to cleanup dependencies, like coreutils and git, because metanorma by itself not counting on them, and on appveyor we will install them by separate command

How do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 very good idea -- let's do that, and can you also help update Metanorma.com (via a PR to https://github.com/riboseinc/metanorma.com/) to reflect this installation step?

**Comment by CAMOBAP795** [comment]
@ronaldtse metanorma pushed to chocolatey, https://github.com/riboseinc/metanorma.com on the way

**Comment by CAMOBAP795** [comment]
@ronaldtse As I see it still wait for manual review, but package automation test passed so I think we can close this one

BTW maybe you got any email with review result (I don't see anything in https://chocolatey.org/packages/metanorma/1.1.4)

**Comment by ronaldtse** [comment]
No email. Is there a way we can ping the moderator?

**Comment by CAMOBAP795** [comment]
@ronaldtse to be honest IDK, Is there some account for chocolatey? maybe there is possible to communicate?

**Comment by ronaldtse** [comment]
I just posted a message there.

**Comment by CAMOBAP795** [comment]
Strange test failed, but looks like because of some internal reasons

https://gist.github.com/choco-bot/98979cf7dd5036bcafda2524d33b3ff1

```
...
Unable to resolve dependency 'chocolatey-core.extension (= 1.3.3)'.
...
```

I will retag to do release again

**Comment by CAMOBAP795** [comment]
Updated package was uploaded to review

**Comment by ronaldtse** [comment]
Hope it all works now!

**Comment by CAMOBAP795** [comment]
- Automation validation passed
 - We are waiting for manual review again

**Comment by CAMOBAP795** [comment]
@ronaldtse maybe you can 'ping' reviewer again?

**Comment by ronaldtse** [comment]
Pinged!

**Comment by ronaldtse** [comment]
https://gist.github.com/choco-bot/f9e4bce4e833342d5bf99fbdfc58f670

It says:

```
2019-02-27 09:03:51,190 356 [INFO ] - [NuGet] Attempting to resolve dependency 'graphviz (= 2.38.0.1)'.
2019-02-27 09:03:51,518 356 [ERROR] - metanorma not installed. An error occurred during installation:
 Unable to resolve dependency 'graphviz (= 2.38.0.1)'.
2019-02-27 09:03:51,581 356 [INFO ] - metanorma package files install completed. Performing other installation steps.
```

Perhaps we should not lock graphviz.

**Comment by ronaldtse** [comment]
And in fact, we should probably loosen the package dependencies. This list can easily cause ongoing maintenance nightmares:

```
2019-02-27 09:02:28,799 356 [INFO ] - [NuGet] Attempting to resolve dependency 'msys2 (= 20180531.0.0)'.
2019-02-27 09:02:47,206 356 [INFO ] - [NuGet] Attempting to resolve dependency 'chocolatey (= 0.10.8)'.
2019-02-27 09:02:48,378 356 [INFO ] - [NuGet] Attempting to resolve dependency 'chocolatey-core.extension (= 1.3.3)'.
2019-02-27 09:03:17,643 356 [INFO ] - [NuGet] Attempting to resolve dependency 'ruby (< 2.6.0)'.
2019-02-27 09:03:20,596 356 [INFO ] - [NuGet] Attempting to resolve dependency 'chocolatey (= 0.10.5)'.
2019-02-27 09:03:20,596 356 [INFO ] - [NuGet] Attempting to resolve dependency 'xsltproc (= 1.1.28.0)'.
2019-02-27 09:03:24,112 356 [INFO ] - [NuGet] Attempting to resolve dependency 'nodejs (= 11.3.0)'.
2019-02-27 09:03:25,690 356 [INFO ] - [NuGet] Attempting to resolve dependency 'nodejs.install (= 11.10.0)'.
2019-02-27 09:03:33,315 356 [INFO ] - [NuGet] Attempting to resolve dependency 'plantuml (= 1.2018.14)'.
2019-02-27 09:03:36,519 356 [INFO ] - [NuGet] Attempting to resolve dependency 'javaruntime (= 6.0.30)'.
2019-02-27 09:03:50,597 356 [INFO ] - [NuGet] Attempting to resolve dependency 'jre8 (= 8.0.191)'.
2019-02-27 09:03:51,190 356 [INFO ] - [NuGet] Attempting to resolve dependency 'graphviz (= 2.38.0.1)'.
```

**Comment by CAMOBAP795** [comment]
> Perhaps we should not lock graphviz.

But we do, it's transitive dependency which comes from `plantuml`

> we should probably loosen the package dependencies. This list can easily cause ongoing maintenance nightmare

If we make `plantuml` "as optional" we can rid of `plantuml`, `jre8`, `javaruntime`, `graphviz`, `chocolatey-core.extension`

I said "as optional" (with brackets) because technically there is no optional dependencies in chocoltey but we can do it as suggested here https://github.com/chocolatey/choco/wiki/CreatePackages#rules-to-be-observed-before-publishing-packages :

> **Split dependencies into multiple packages.** Try to split up packages as much as possible. If for example a program comes with additional modules/installers that are optional, make different packages for them instead of including all the things into one package. This idea is already widely applied for Linux packages, because it leads to a more lightweight system and reduces potential issues and conflicts.

@ronaldtse how do you think should we split `metanorma` package?

**Comment by ronaldtse** [comment]
I don't think we can split it easily. Does this mean that `plantuml` cannot be installed now because the `graphviz` version dependency cannot be fulfilled?

**Comment by CAMOBAP795** [comment]
@ronaldtse to be honest I'm not sure that ` Unable to resolve dependency 'graphviz (= 2.38.0.1)'.` error is persistent. 

We never experienced this error during run of our CI, and we have added `plantuml` long time ago.  

Maybe we can get some details from validator about this?

**Comment by ronaldtse** [comment]
And the package has failed automated validation again. 

Now it’s “msys2” cannot be found. 

https://gist.github.com/29fb4220f7e955b9b3043ff4fbd48219

**Comment by CAMOBAP795** [comment]
Now it's clearly network issue

> 2019-02-27 13:00:13,303 2808 [WARN ] - [NuGet] Could not connect to the feed specified at 'https://chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.

BTW @ronaldtse maybe you can add me to metanorma team on chocolatey (if such exists), just to not bother you with copy-paste, and I will be able reply ASAP

**Comment by ronaldtse** [comment]
@CAMOBAP795 yes let me add you to the chocolatey package. Can you give me your account handle at Chocolatey?

**Comment by ronaldtse** [comment]
Done.

**Comment by CAMOBAP795** [comment]
@ronaldtse I just found that there is option to run test which chocolatey runs locally https://github.com/chocolatey/chocolatey-test-environment

I think it's make sense to add this to CI

@ronaldtse how do you think?

**Comment by ronaldtse** [comment]
@CAMOBAP795 sure, but how do you run Chocolatey "locally" in a CI?

**Comment by CAMOBAP795** [comment]
@ronaldtse sorry for confusion, by 'locally' I mean outside chocolatey build server

**Comment by ronaldtse** [comment]
Then you mean something like Gitlab?

**Comment by CAMOBAP795** [comment]
@ronaldtse I will just update appveyor configuration

**Comment by ronaldtse** [comment]
@CAMOBAP795 it seems that Chocolatey testing can't finish on our package (over 52 minutes until it got truncated). Would splitting the package help? Or maybe not since there is still a lot to install?

**Comment by CAMOBAP795** [comment]
@ronaldtse FYI https://github.com/chocolatey/choco/issues/1756 reported to chocolatey, I will debug it locally with choco sources

**Comment by CAMOBAP795** [comment]
Original issue related to appveyor only https://github.com/Microsoft/azure-pipelines-image-generation/issues/742#issuecomment-472852611

**Comment by CAMOBAP795** [comment]
I'm working on set up of https://github.com/chocolatey/chocolatey-test-environment

**Comment by CAMOBAP795** [comment]
Unfortunately impossible to automate it

```
Packages requiring reboot:
 - vagrant (exit code 3010)
The recent package changes indicate a reboot is necessary.
```

Let's wait for verification complete

**Comment by CAMOBAP795** [comment]
https://chocolatey.org/packages/metanorma/1.1.4 - appproved

@ronaldtse I think we can close this task

**Comment by ronaldtse** [comment]
Closed!
