### ISSUE TITLE
URGENT: Metanorma depends on the Git command

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-metanorma#25]
In `appveyor.yml` we specify the following packages to be installed.

`  - choco install -y git make gnuwin32-coreutils.portable sed`

Metanorma MUST DEPEND on these chocolatey packages. `git` in particular is used for Metanorma to download templates, it is a "hard" dependency now.

**Comment by ronaldtse** [comment]
@CAMOBAP795 we need your help. Thanks.

**Comment by CAMOBAP795** [comment]
`make gnuwin32-coreutils.portable sed` used implicitly via `Makefile` in this case we need to add `grep` too because it recently was introduced in `Makefile` (and as result in `Makefile.win` too)

**Comment by CAMOBAP795** [comment]
@ronaldtse https://chocolatey.org/packages/metanorma/1.1.7 - released, let me know if anything else needs to be done in the scope of this ticket

**Comment by CAMOBAP795** [comment]
Done
