### ISSUE TITLE
(URGENT) Issue with Chocolatey metanorma installation needing manual install of gems

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-metanorma#30]
A user has reported that after installing the latest Chocolatey package, he had to:

1. Manually install metanorma gems (https://www.metanorma.com/software/metanorma-cli/docs/installation/#installing-the-gems)

2. Manually install gem `tzinfo-data` to get rid of the https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors 

3. Was shown the following error:
```
        12: from C:/tools/ruby25/bin/metanorma:23:in `<main>'
        11: from C:/tools/ruby25/bin/metanorma:23:in `load'
        10: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/metanorma-cli-1.1.8/exe/metanorma:11:in `<top (required)>'
         9: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         7: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/setup.rb:10:in `<top (required)>'
         6: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler.rb:107:in `setup'
         5: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:26:in `setup'
         4: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:26:in `map'
         3: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:148:in `each'
         2: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:148:in `each'
         1: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:31:in `block in setup'
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:319:in `check_for_activated_spec!': You have already activated isodoc 0.9.23, but your Gemfile requires isodoc 0.9.22. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

Finally the user had to run `bundle exec metanorma ...` and it worked.

@CAMOBAP795 can you attempt to reproduce these issues and provide the necessary PRs to ensure this doesn't happen?

The user should only need to install Chocolatey Metanorma, and can run `metanorma ...` directly.

Thanks!

**Comment by CAMOBAP795** [comment]
> https://www.metanorma.com/software/metanorma-cli/docs/installation/#installing-the-gems

Let me check but we switched out `ruby-xslt` a couple of releases ago

> Manually install gem tzinfo-data to get rid of the 

AFAIK it needs only by `metanorma-nist` correct me if I'm wrong, and I have fixed it some time ago https://github.com/metanorma/metanorma-nist/commit/56776aee

> Finally the user had to run `bundle exec metanorma ...` and it worked.

Good point because currently on CI we test only `metanorma help` and `bundle exec metanorma ...` commands

Let me check all those points more preciselly

**Comment by CAMOBAP795** [comment]
@ronaldtse we need more details because I have tested steps on clean windows 10 installation and steps

```
cinst msys2 --params /NoUpdate -y
cinst metanorma -y
```

Works, I have tested:
 - `metanorma help`
 - `metanorma new test -t csd -d advisory`

And it works perfectly

@ronaldtse can we request more details from a person who have troubles:
 - windows os version
 - installation log
 - which ruby version was available on this machine

**Comment by ronaldtse** [comment]
This user was upgrading from Metanorma 1.17. Maybe there is an issue with upgrading?

**Comment by CAMOBAP795** [comment]
@ronaldtse thanks for note, I will check

**Comment by CAMOBAP795** [comment]
@ronaldtse I checked the upgrade scenario 

```
cinst metanorma -y --version 1.1.7
choco upgrade metanorma -y
```

Ruby will keep both `metanorma-cli@1.1.7` and `metanorma-cli@1.1.8` (let me know if this behavior need to be changed)

To continue investigation I need:
 - the exact metanorma command which leads to stack-trace above
 - the output of `gem list metanorma`
 - chocolatey upgrade log if it exists

**Comment by ronaldtse** [comment]
The user is using Windows 10, with Ruby version: `ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]` (it was installed via RIDK/Chocolatey)

He ran:

```
gem install isodoc
gem install metanorma-cli
gem install metanorma-nist
refreshenv 
```

Then, he tried metanorma:

```
metanorma -t nist -x html NIST.SP.800-116r1.adoc
```

but still got the same message as above. Same result, even after exiting and then opening a new shell.
 
Then he tried `bundle exec…`, but IMMEDIATELY got the following error:
 
```
Traceback (most recent call last):
        28: from C:/tools/ruby25/bin/bundle:23:in `<main>'
        27: from C:/tools/ruby25/bin/bundle:23:in `load'
        26: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:21:in `<top (required)>'
        25: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        24: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        23: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:5:in `<top (requ
red)>'
        22: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        21: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendored_thor.rb:8:in `<top (requir
d)>'
        19: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        18: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:2:in `<top
required)>'
        16: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        15: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        14: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:8:in `
top (required)>'
        13: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        12: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        11: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/line_editor.rb
2:in `<top (required)>'
        10: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         9: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         8: from C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/line_editor/re
dline.rb:2:in `<top (required)>'
         7: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         6: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from C:/tools/ruby25/lib/ruby/site_ruby/readline.rb:8:in `<top (required)>'
         4: from C:/tools/ruby25/lib/ruby/site_ruby/readline.rb:10:in `<module:Readline>'
         3: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from C:/tools/ruby25/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         1: from C:/tools/ruby25/lib/ruby/site_ruby/rbreadline.rb:17:in `<top (required)>'
C:/tools/ruby25/lib/ruby/site_ruby/rbreadline.rb:1097:in `<module:RbReadline>': HOME environment variable (or HOMEDRIVE
and HOMEPATH) must be set and point to a directory (RuntimeError)
```

Looks like HOME or related variables went missing?

I found these two articles with potential solutions, not sure if it worked for him:
* https://wilcovanes.ch/articles/development/rbreadline-home-environment-variable-issue-on-windows/
* https://stackoverflow.com/questions/39179377/windows-bundle-install-home-environment-variable-or-homedrive-and-homepath-mu

**Comment by CAMOBAP795** [comment]
Those variables defined by OS, according to links above most relevant case can be this https://stackoverflow.com/a/39301638/902217

@ronaldtse may we request the client to run `set home` and send a response to use (we don't need exact names of user or machine so they can be replaced)

**Comment by ronaldtse** [comment]
The user doesn't seem to have this problem any more. We will investigate this again if someone comes up with it again.
