### ISSUE TITLE
Add `idnits` installation

### ISSUE THREAD

**Issue by CAMOBAP795** [metanorma/chocolatey-metanorma#32]
Let's wait for https://pypi.org/project/id2xml/ the release 

Currently problem is https://github.com/metanorma/chocolatey-metanorma/pull/31#issuecomment-498837257

+ port bash bellow

export IDNITS_URL=https://tools.ietf.org/tools/idnits/
export IDNITS_VER=$(curl -Ls $IDNITS_URL | grep -e 'tgz' | sed -e 's/.*\(idnits-.*\).tgz.*/\1/') ; echo ${IDNITS_VER}
curl -SL ${IDNITS_URL}${IDNITS_VER} | tar xzv
export PATH=$(pwd)/${IDNITS_VER}:${PATH}

**Comment by CAMOBAP795** [comment]
I got an answer

```
Hi Alexander,

The idnits version you found is an incomplete rewrite of the original
idnits.  At this time, you should be using the original; the rewrite
will be completed during the coming months.

For the current version, check https://tools.ietf.org/tools/idnits.
```

**Comment by ronaldtse** [comment]
OK, let's change back to previous behavior for now.

**Comment by ronaldtse** [comment]
@CAMOBAP795 has this been fixed?

**Comment by CAMOBAP795** [comment]
@ronaldtse unfortunately we still blocked, I will watch out for this if it's releases, If this really critical, we may try to patch this python module during installation, should we?

**Comment by ronaldtse** [comment]
The point is we can't wait for their `idnits` because they don't seem to have a release date. Can we specify an older version? Or use the manual downloaded version?

**Comment by CAMOBAP795** [comment]
@ronaldtse  I got your point, I think older version will not work due to the same problem we can try to get last available version from CVS system

**Comment by CAMOBAP795** [comment]
Done
