### ISSUE TITLE
libxml2/libxslt package

### ISSUE THREAD

**Issue by jayvdb** [metanorma/chocolatey-metanorma#33]
The voodoo in this package for using @geraldcombs's xsltproc to set up libxml2/libxslt to build against is awesome.

I think it would be very useful for it to become a separate package , or be included into the xsltproc package .  A quick-ish hack would be for the new package to include no files but merely post-process xsltproc, set envvars pointing to the correct include/lib location, and set/update `PKG_CONFIG_PATH`, etc.

It might even be possible to fix the .pc files in xsltproc/dist/lib/pkgconfig/ and get those to be usable with a pkgconfig.

The new package could then be a stable dependency for any packages needing a native libxml2/libxslt-dev 

Is @metanorma interested in hosting such a new package , since you did the initial work?

**Comment by ronaldtse** [comment]
@jayvdb Thank you for the comment! We are certainly open in hosting such a package. Amazed that you found our package. The `pkgconfig` bit is interesting as well.

@CAMOBAP795 do you have time to implement this? Thanks!

**Comment by jayvdb** [comment]
I was googling for `chocolatey "xslt-config"` where this package and https://github.com/glejeune/ruby-xslt/issues/9#issuecomment-443025108 are leading results.

https://chocolatey.org/packages/libxml2 and https://chocolatey.org/packages/libxslt are both rejected packages, owned by @jakepetroules hosted at https://github.com/jakepetroules/chocolatey-packages .  That might also be a viable home if Jake is intending to keep maintaining them, or Jake might be happy to let someone else join as maintainer of those (He did that with https://chocolatey.org/packages/android-ndk which moved to https://github.com/ripclawffb/chocolatey-android-ndk)

**Comment by jayvdb** [comment]
fwiw if metanorma/ruby is using windows compilers under the covers, there is a choco package for vswhere , which looks like it might be useful for locating a working compiler; c.f. https://github.com/microsoft/vswhere/issues/187

**Comment by CAMOBAP795** [comment]
@jayvdb at this point `chocolatey-metanorma` don't use `xsltproc` package, and highly likelly will not use it in future

Just to be on the same page, what the issue `xsltproc` you experienced with? Missing `*-config` script or anything else?

> fwiw if metanorma/ruby is using windows compilers under the covers

We use mingw for native extension compilation

**Comment by jayvdb** [comment]
I see it has been removed recently. https://github.com/metanorma/chocolatey-metanorma/commit/7ac4e88969f7f87828ed4cfec2413476c443914d#diff-3824e4119909511f5b298c2c4125ca1c

All the more reason for this trick to be saved so others can use it when necessary.

**Comment by CAMOBAP795** [comment]
@jayvdb sorry for the long silence, agree with you now I think about potential use cases. In our cases we use such workaround because `glejeune/ruby-xslt` wasn't initially designed for compiling and using on windows platform, in my opinion, it's a too specific task

If you see another potential use cases, please let me know

**Comment by jayvdb** [comment]
@CAMOBAP795 , my use case is compiling python library @lxml , which needs to compile against libxml2 and libxslt . They do provide binary versions for some Windows releases, which is ok most of the time, but as an example they didnt build a wheel for Python 3.4 64 bit for version 3.8.0, which is the last version before v4 was released and often older software needs v3.* , but then blows up on 64 bit Windows Python 3.4 because it needs to be compiled (and then goes looking for `libxslt-config`, while every other reasonable Python version has pre-compiled versions.  And v3.7 and earlier is worse, with piecemeal pre-compiled support, and the only way to know which versions will install without knowing how to read the list of options available at https://pypi.org/simple/lxml/

**Comment by CAMOBAP795** [comment]
@jayvdb, actually, we didn't have ported version of `*-config` (which originally implemented in bash AFAIK). 

As you may see in https://github.com/metanorma/chocolatey-metanorma/commit/7ac4e88969f7f87828ed4cfec2413476c443914d#diff-3824e4119909511f5b298c2c4125ca1c we just creating minimal `libxslt-config` and  `xml2-config`

So we just need them to keep `rake` happy and pass all compiler input via `--with-*` options

I think a longterm solution will be to have an actual version of `*-config.bat` but it will be not easy to implement them because we will need to support several toolchains

And unfortunately, I don't see a good solution here, we cannot create a package with just empty `*-config.bat` inside of it.

**Comment by jayvdb** [comment]
The lack of -config doesnt hurt my use case.  lxml can be provided the cflags and libs it needs via environment variables.  It just looks for the -config as its first method of trying to obtain that information.  It still tries to build anyways, and I was able to get the compile happy so I am confident this approach also works for lxml.  Sorry I wasnt clear about that.  The only part I didnt get working was adding the correct vs runtime .lib to keep the linker happy, as it was failing due to some stdio names which had become inline-d functions.  I just ran out of time, and knew that solving it once wont be sufficient, as the choco package will be updated and it will break again, so went looking for who else may be interested in a solution so it is better maintained.

**Comment by CAMOBAP795** [comment]
> The only part I didnt get working was adding the correct vs runtime .lib to keep the linker happy, as it was failing due to some stdio names which had become inline-d functions.

@jayvdb hm, on my side (when worked with ruby gem) I faced only with library not found issue, could you please show an example of such problems?

**Comment by jayvdb** [comment]
Hmm, I cant find those builds easy - searching through AppVeyor builds isnt simple.  I've done some rebuilds of the branch I believe was the 'latest'.

Seemingly successful using msys2 pacman's libs, but I didnt run a full test suite on it
https://ci.appveyor.com/project/jayvdb/coala-bears/build/job/ofkl5b0c7e4by1e7#L154

Successful link using a similar trick as your solution, but again I didnt run a full test suite on it
https://ci.appveyor.com/project/jayvdb/coala-bears/builds/25797273/job/xh2fom762lotxool

I fiddled with the .pc files.

The important bits are
```cmd
sed -i 's:^prefix=.*:prefix=/c/ProgramData/chocolatey/lib/xsltproc/dist/:' %ChocolateyInstall%\lib\xsltproc\dist\lib\pkgconfig\libxml-2.0.pc
set "PATH=%ChocolateyInstall%\lib\xsltproc\dist\bin;%PATH%"
set "PKG_CONFIG_PATH=/c/ProgramData/chocolatey/lib/xsltproc/dist/lib/pkgconfig:;/c/ProgramData/chocolatey/lib/xsltproc/dist/lib/pkgconfig;%ChocolateyInstall%\lib\xsltproc\dist\lib\pkgconfig;"
```

I think my linking troubles may have occurred when using the AppVeyor `Visual Studio 2017` image.

**Comment by CAMOBAP795** [comment]
@jayvdb thanks, I think I understood the problem, I used a little bit different approach to solve the issue (it's more looks like a workaround) so looks like there is nothing to publish

I'm going to close this ticket

**Comment by ronaldtse** [comment]
@jayvdb thanks for explaining where you came from. In our case it was merely a workaround but nothing long lasting...
