### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-metanorma#34]

**Comment by ronaldtse** [comment]
ping @CAMOBAP795

**Comment by ronaldtse** [comment]
Ping @CAMOBAP795 , I've removed AppVeyor already.

**Comment by CAMOBAP795** [comment]
Not fixed yet, list of issues to fix:
 - [ ] 'metanorma' is not recognized as an internal or external command,
 - [ ] INFO: Could not find "xml2rfc".

**Comment by ronaldtse** [comment]
API key is now `secrets.CHOCOLATEY_API_KEY`.

**Comment by CAMOBAP795** [comment]
Merged
