### ISSUE TITLE
Installation of yq.exe not included

### ISSUE THREAD

**Issue by anermina** [metanorma/chocolatey-metanorma#35]
yq.exe file is not automatically installed during Metanorma installation via Chocolatey package on Windows. Thus, make command fails with the following output:

PS D:\Upwork\mn-samples-itu-master> make -f Makefile.win SHELL=cmd
A subdirectory or file C:\Users\Nermina\.cache\xml2rfc already exists.
'yq' is not recognized as an internal or external command,
operable program or batch file.

**Comment by CAMOBAP795** [comment]
@ronaldtse I propose to create `yq` as a separate chocolatey package, make sense?

**Comment by ronaldtse** [comment]
`yq` is not technically needed in Metanorma. It is only the `Makefile` that uses it; I don't think we should include that in the Chocolatey package.

**Comment by CAMOBAP795** [comment]
@ronaldtse but maybe make sense to wrap it in separate chocolatey package

**Comment by ronaldtse** [comment]
@CAMOBAP795 OK, let's do that.

**Comment by ronaldtse** [comment]
@CAMOBAP795 but we must fix LaTeXML chocolatey package first.

**Comment by CAMOBAP795** [comment]
@ronaldtse there is no issues reported for https://github.com/metanorma/chocolatey-latexml maybe you mean snap for LaTeXML (moving to GitHub actions)?

**Comment by ronaldtse** [comment]
> there is no issues reported for https://github.com/metanorma/chocolatey-latexml maybe you mean snap for LaTeXML (moving to GitHub actions)?

@CAMOBAP795 yes I got confused 😓  We need to fix the snap package to bring down the running times.

**Comment by CAMOBAP795** [comment]
@ronaldtse I know it's not a top priority but could you please create a repository `chocolatey-yq` (for https://github.com/mikefarah/yq) I will add it to chocolatey later

**Comment by ronaldtse** [comment]
Actually, let's migrate away from `yq` because it is not a Metanorma dependency. I will create a new ticket for `metanorma-cli` that uses Ruby to incorporate the current `Makefile` functionality to replace `yq`.

**Comment by CAMOBAP795** [comment]
closed based on the comment above
