### ISSUE TITLE
Add secrets.METANORMA_CI_PAT_TOKEN

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-metanorma#47]
According to last run https://github.com/metanorma/chocolatey-metanorma/runs/751671464?check_suite_focus=true it looks like secrets.METANORMA_CI_PAT_TOKEN missing

@ronaldtse could you please have a look

**Comment by ronaldtse** [comment]
It was because metanorma-ci user didn't have access, should be fixed now.

**Comment by ronaldtse** [comment]
It's fixed. Closing.
