### ISSUE TITLE
imagemagick.tool (exited 404)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-metanorma#53]
All samples repos failing for windows:

> - imagemagick.tool (exited 404) - Error while running 'C:\ProgramData\chocolatey\lib\imagemagick.tool\tools\chocolateyInstall.ps1'.

Full log https://github.com/metanorma/ogc-tcpnp/runs/1302596947?check_suite_focus=true

**Comment by CAMOBAP** [comment]
`chocolatey.tool` broken https://chocolatey.org/packages/imagemagick.tool#versionhistory (datils in the comments for the link)

we don't have this dependency anymore because latexml removed from the dependency list 

we need a new release

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP for following this up!

**Comment by CAMOBAP** [comment]
New version is released
