### ISSUE TITLE
Verify Chocolatey installation on Windows succeed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/chocolatey-metanorma#54]
A user has reported that Chocolatey installation on Windows failed with the message "Error: specified file setup doesn't exists".

![image](https://user-images.githubusercontent.com/11865/110801322-14d48f00-82b8-11eb-82dd-3d92b2450cbc.png)

**Comment by ronaldtse** [comment]
@CAMOBAP says the error can be safely ignored since it was remnant from the previous `metanorma setup` command which has been superseded by default behavior.

**Comment by CAMOBAP** [comment]
Release on the way

**Comment by CAMOBAP** [comment]
1.4.5.1 - approved
