### ISSUE TITLE
Find proper test environemnt

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-metanorma#57]
After https://github.com/metanorma/packed-mn/issues/118 it looks like GitHub Actions test environment can hide some issues. Mostly because a lot of preinstalled software

Possible solutions:
 - [ ] check environment where chocolatey's pre-publish tests executes https://community.chocolatey.org/courses/creating-chocolatey-packages/building-testing-and-pushing, and review possibilities to run custom tests
 - [ ] free third-party services which can be used to test metanorma on windows
 - [ ] go back to appveyour just for test porpouse 

cc @ronaldtse

**Comment by ronaldtse** [comment]
The available Windows runners are here:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

I believe it is possible to run Docker Windows containers on these runners so that we have a clean environment to start.

**Comment by CAMOBAP** [comment]
Really nice finding I never thought in this direction, thanks @ronaldtse

**Comment by ronaldtse** [comment]
Running Docker Window images: https://github.com/docker/labs/blob/master/windows/windows-containers/WindowsContainers.md

**Comment by CAMOBAP** [comment]
Done
