### ISSUE TITLE
Check benefits of winget vs chocolatey

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/chocolatey-metanorma#62]
https://github.com/microsoft/winget-pkgs

cc @ronaldtse

**Comment by ronaldtse** [comment]
So it has to be an installation package. 

> At this time installers must either be MSIX, MSI or .exe application installers. Standalone or portable executables, compressed .zip files, and fonts are not currently supported.

**Comment by ronaldtse** [comment]
@CAMOBAP we can wrap metanorma in an installation package using MSIX (https://github.com/microsoft/msix-packaging), which also allows us to code sign the package.

**Comment by ronaldtse** [comment]
Let's continue over at https://github.com/metanorma/packed-mn/issues/159
